import { BookingRequest } from "./types";

export interface Artist {
  id: string;
  name: string;
  genre: string;
  baseLocation: string;
  coordinates: { lat: number; lng: number };
}

export const mockArtists: Artist[] = [
  {
    id: "artist-1",
    name: "DJ Supreme",
    genre: "Hip Hop / Electronic",
    baseLocation: "Los Angeles, CA",
    coordinates: { lat: 34.0522, lng: -118.2437 },
  },
  {
    id: "artist-2",
    name: "Luna Nova",
    genre: "Deep House / Techno",
    baseLocation: "Miami, FL",
    coordinates: { lat: 25.7617, lng: -80.1918 },
  },
  {
    id: "artist-3",
    name: "The Vibe Collective",
    genre: "R&B / Soul",
    baseLocation: "Atlanta, GA",
    coordinates: { lat: 33.749, lng: -84.388 },
  },
];

// Location coordinates for distance calculations
export const locationCoordinates: Record<string, { lat: number; lng: number }> = {
  "Miami, FL": { lat: 25.7617, lng: -80.1918 },
  "Atlanta, GA": { lat: 33.749, lng: -84.388 },
  "Las Vegas, NV": { lat: 36.1699, lng: -115.1398 },
  "Dubai, UAE": { lat: 25.2048, lng: 55.2708 },
  "Houston, TX": { lat: 29.7604, lng: -95.3698 },
  "Los Angeles, CA": { lat: 34.0522, lng: -118.2437 },
  "Chicago, IL": { lat: 41.8781, lng: -87.6298 },
  "New York, NY": { lat: 40.7128, lng: -74.006 },
  "San Francisco, CA": { lat: 37.7749, lng: -122.4194 },
  "Denver, CO": { lat: 39.7392, lng: -104.9903 },
  "Seattle, WA": { lat: 47.6062, lng: -122.3321 },
  "Austin, TX": { lat: 30.2672, lng: -97.7431 },
  "Nashville, TN": { lat: 36.1627, lng: -86.7816 },
  "Phoenix, AZ": { lat: 33.4484, lng: -112.074 },
};

export const mockBookingRequests: BookingRequest[] = [
  // DJ Supreme requests
  {
    id: "BR-001",
    artistName: "DJ Supreme",
    eventType: "club",
    proposedFee: 25000,
    eventDate: "2026-05-15",
    eventLocation: "Miami, FL",
    submissionDate: "2026-04-05",
    venueName: "LIV Nightclub",
    contactName: "Marcus Johnson",
    contactEmail: "marcus@livmiami.com",
    notes: "VIP section appearance, 2-hour minimum. Bottle service included.",
    status: "review",
  },
  {
    id: "BR-002",
    artistName: "DJ Supreme",
    eventType: "lounge",
    proposedFee: 8000,
    eventDate: "2026-04-20",
    eventLocation: "Atlanta, GA",
    submissionDate: "2026-04-03",
    venueName: "Compound Atlanta",
    contactName: "Tasha Williams",
    contactEmail: "tasha@compoundatl.com",
    notes: "Album release party hosting gig.",
    status: "reject",
    reasonCode: "below_minimum_fee",
  },
  {
    id: "BR-003",
    artistName: "DJ Supreme",
    eventType: "concert",
    proposedFee: 45000,
    eventDate: "2026-04-10",
    eventLocation: "Las Vegas, NV",
    submissionDate: "2026-04-06",
    venueName: "Drai's Nightclub",
    contactName: "Alex Chen",
    contactEmail: "alex.chen@drais.com",
    notes: "Headlining performance for grand opening weekend.",
    status: "manual_review",
    manualReviewReason: "high_value_opportunity",
  },
  {
    id: "BR-004",
    artistName: "DJ Supreme",
    eventType: "private",
    proposedFee: 75000,
    eventDate: "2026-06-20",
    eventLocation: "Dubai, UAE",
    submissionDate: "2026-04-01",
    venueName: "Private Residence",
    contactName: "Ahmed Al-Rashid",
    contactEmail: "ahmed@privateevents.ae",
    notes: "Private birthday celebration for high-profile client. All travel expenses covered.",
    status: "review",
  },
  {
    id: "BR-005",
    artistName: "DJ Supreme",
    eventType: "club",
    proposedFee: 11000,
    eventDate: "2026-04-25",
    eventLocation: "Houston, TX",
    submissionDate: "2026-04-04",
    venueName: "Spire Nightclub",
    contactName: "Derek Thompson",
    contactEmail: "derek@spirehouston.com",
    notes: "Grand opening appearance, negotiable on fee.",
    status: "manual_review",
    manualReviewReason: "borderline_fee",
  },
  {
    id: "BR-006",
    artistName: "DJ Supreme",
    eventType: "festival",
    proposedFee: 30000,
    eventDate: "2026-05-30",
    eventLocation: "Los Angeles, CA",
    submissionDate: "2026-04-02",
    venueName: "Academy LA",
    contactName: "Jessica Park",
    contactEmail: "jessica@academyla.com",
    notes: "Memorial Day weekend event. Full production support provided.",
    status: "review",
  },
  
  {
    id: "BR-008",
    artistName: "DJ Supreme",
    eventType: "club",
    proposedFee: 20000,
    eventDate: "2026-05-08",
    eventLocation: "New York, NY",
    submissionDate: "2026-04-06",
    venueName: "Marquee NYC",
    contactName: "Sarah Miller",
    contactEmail: "sarah@marqueenyc.com",
    notes: "Friday night appearance, potential for recurring bookings.",
    status: "review",
  },
  // Luna Nova requests
  {
    id: "BR-009",
    artistName: "Luna Nova",
    eventType: "club",
    proposedFee: 18000,
    eventDate: "2026-05-22",
    eventLocation: "San Francisco, CA",
    submissionDate: "2026-04-04",
    venueName: "Audio SF",
    contactName: "Ryan Chen",
    contactEmail: "ryan@audiosf.com",
    notes: "Saturday night headliner slot, 3-hour set.",
    status: "review",
  },
  {
    id: "BR-010",
    artistName: "Luna Nova",
    eventType: "festival",
    proposedFee: 35000,
    eventDate: "2026-06-15",
    eventLocation: "Denver, CO",
    submissionDate: "2026-04-03",
    venueName: "Red Rocks Amphitheatre",
    contactName: "Amanda Brooks",
    contactEmail: "amanda@redrocks.com",
    notes: "Electronic music festival, sunset slot on main stage.",
    status: "review",
  },
  {
    id: "BR-011",
    artistName: "Luna Nova",
    eventType: "lounge",
    proposedFee: 6000,
    eventDate: "2026-04-28",
    eventLocation: "Seattle, WA",
    submissionDate: "2026-04-05",
    venueName: "Monkey Loft",
    contactName: "Jake Wilson",
    contactEmail: "jake@monkeyloft.com",
    notes: "Underground techno night, intimate venue.",
    status: "reject",
    reasonCode: "below_minimum_fee",
  },
  {
    id: "BR-012",
    artistName: "Luna Nova",
    eventType: "private",
    proposedFee: 50000,
    eventDate: "2026-07-04",
    eventLocation: "Miami, FL",
    submissionDate: "2026-04-02",
    venueName: "Private Yacht",
    contactName: "Sofia Martinez",
    contactEmail: "sofia@luxevents.com",
    notes: "Independence Day celebration on mega yacht. All expenses covered.",
    status: "review",
  },
  // The Vibe Collective requests
  {
    id: "BR-013",
    artistName: "The Vibe Collective",
    eventType: "concert",
    proposedFee: 28000,
    eventDate: "2026-05-10",
    eventLocation: "Austin, TX",
    submissionDate: "2026-04-04",
    venueName: "ACL Live",
    contactName: "Marcus Green",
    contactEmail: "marcus@acllive.com",
    notes: "Opening for major R&B artist on tour.",
    status: "review",
  },
  {
    id: "BR-014",
    artistName: "The Vibe Collective",
    eventType: "corporate",
    proposedFee: 22000,
    eventDate: "2026-06-01",
    eventLocation: "Nashville, TN",
    submissionDate: "2026-04-05",
    venueName: "Bridgestone Arena",
    contactName: "Linda Thompson",
    contactEmail: "linda@musiccityevents.com",
    notes: "Annual music industry awards after-party.",
    status: "review",
  },
  {
    id: "BR-015",
    artistName: "The Vibe Collective",
    eventType: "club",
    proposedFee: 9500,
    eventDate: "2026-04-22",
    eventLocation: "Phoenix, AZ",
    submissionDate: "2026-04-03",
    venueName: "Maya Day + Nightclub",
    contactName: "Chris Patel",
    contactEmail: "chris@mayaclub.com",
    notes: "Weekend appearance, potential for residency.",
    status: "manual_review",
    manualReviewReason: "borderline_fee",
  },
  {
    id: "BR-016",
    artistName: "The Vibe Collective",
    eventType: "festival",
    proposedFee: 40000,
    eventDate: "2026-08-15",
    eventLocation: "Atlanta, GA",
    submissionDate: "2026-04-01",
    venueName: "Music Midtown",
    contactName: "Jasmine Cole",
    contactEmail: "jasmine@musicmidtown.com",
    notes: "Main stage performance at hometown festival.",
    status: "review",
  },
];
